### ISSUE TITLE
Chap4 alignments.R

### ISSUE THREAD

**Issue by seifried** [csortu/MDAuR#2] opened 2017-03-05 16:52 UTC
Aloha,
Apologies if noob error
Trouble with script ca. line 85?
1st: I updated script to agree with text by adding the "unlist" command.
But that did not fix the error. With or without "unlist" I get console output as copied below
(listings of genehits and genelist both look good, with a "subjectHits" column in genehits listing) 
I'm using most recent Win10/R/RStudio/BioC/
Thanks

 gids <- unlist(genelist[unique(genehits@subjectHits)]$gene_id)
Error in unique(genehits@subjectHits) : 
 no slot of name "subjectHits" for this object of class "SortedByQueryHits"

**Comment by csortu** [comment] 2017-03-06 12:38
Thanks for your comment. The problem is caused by a small change in the GenomicAlignments package. They have renamed the subjectHits to "to" slot. I have committed changes to GitHub, but you can update the code to this:

gids <- genelist[unique(genehits@to)]$gene_id

And it should work right now.

There is another change while generating gene.range. It should read:

gene.range <- genes(txdb,filter=vals)

I hope this will solve your problem.

**Comment by seifried** [comment] 2017-03-07 18:07
Thanks for also fixing that final trks line as well.

**Closed as completed** 2017-03-07 18:41 UTC
Labels: bug
